#!/usr/bin/env python3
"""Generate the offline reader and plain-text distribution notices from reviewed sources.

No network or build cache is used. --check verifies generated bytes and complete
coverage of the resolved runtime + Java desugaring dependency inventory.
"""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LICENSES = ROOT / "licenses"
ASSETS = ROOT / "app/src/main/assets"


def require(condition, message):
    if not condition:
        raise SystemExit("FAIL: " + message)


def generate():
    catalog = json.loads((LICENSES / "catalog.json").read_text())
    require(catalog["format"] == 1, "unsupported notices catalog")
    entries = catalog["entries"]
    coordinates = [c for entry in entries for c in entry["coordinates"]]
    inventory = [line.split("\t")[0] for line in (LICENSES / "runtime-dependencies.tsv").read_text().splitlines()]
    require(len(set(coordinates)) == len(coordinates), "duplicate dependency attribution")
    require(set(coordinates) == set(inventory), "notices do not cover the resolved dependencies")
    require(len({e["id"] for e in entries}) == len(entries), "duplicate component id")
    public = []
    output = {}
    documents = {}
    plain = ["Sprich — licenses and notices\n",
             "Third-party code and downloaded models retain their own licenses.\n"
             "Original license wording, including any standard license appendix, is preserved.\n"
             "Component versions and source locations are listed below. Model files are downloaded separately.\n"]
    for entry in entries:
        require(entry["documents"], "missing license: " + entry["id"])
        view = {k: entry[k] for k in ("id", "name", "version", "license", "source", "description", "attribution")}
        view["documents"] = []
        plain += ["\n" + entry["name"], " · ".join(filter(None, [entry["version"], entry["license"]])),
                  entry["description"], entry["attribution"], "Source: " + entry["source"]]
        for doc in entry["documents"]:
            relative = Path(doc["path"])
            require(relative.parts[0] == "texts" and ".." not in relative.parts, "unsafe notice path")
            data = (LICENSES / relative).read_bytes()
            require(data.strip(), "empty notice: " + str(relative))
            require(hashlib.sha256(data).hexdigest() == doc["sha256"], "unreviewed license change: " + str(relative))
            require(doc["source"], "missing source provenance: " + str(relative))
            output[ASSETS / "notices" / relative] = data
            view["documents"].append({"title": doc["title"], "path": doc["path"]})
            if doc["path"] not in documents:
                documents[doc["path"]] = (len(documents) + 1, doc["title"], data)
            number, _, _ = documents[doc["path"]]
            plain.append(f"Document {number}: {doc['title']}")
        public.append(view)
    for number, title, data in documents.values():
        plain += [f"\n\nDocument {number} — {title}\n", data.decode("utf-8")]
    output[ASSETS / "notices/index.json"] = (json.dumps(public, ensure_ascii=False, indent=2) + "\n").encode()
    full = ("\n".join(plain).rstrip() + "\n").encode()
    output[LICENSES / "THIRD_PARTY_NOTICES.txt"] = full
    output[ASSETS / "THIRD_PARTY_NOTICES.txt"] = full
    return output


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = generate()
    for path, data in outputs.items():
        if args.check:
            require(path.is_file() and path.read_bytes() == data, "stale generated notice: " + str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    for path in (ASSETS / "notices").rglob("*"):
        if path.is_file() and path not in outputs:
            require(not args.check, "obsolete packaged notice: " + str(path))
            path.unlink()
    print("PASS: complete dependency coverage, source hashes and generated offline notices")


if __name__ == "__main__":
    main()
